language: java
jdk:
  - oraclejdk7
before_install:
  - wget https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_linux_amd64.zip --no-check-certificate
  - unzip consul_0.6.4_linux_amd64.zip
  - ./consul agent -server -bootstrap -data-dir data &
script: mvn clean test
